### ISSUE TITLE
Motivación para simular un Watch

### ISSUE THREAD

**Issue by neverkas** [RaniAgus/so-project-template#16]
Buenas, quería saber si se podría implementar algo parecido a un **watch**.

En un mini proyecto aparte había agregado lo siguiente (que funcionaba bien)

```
.PHONY: watch
watch:
	while true; do $(MAKE) -q || $(MAKE); sleep 1; done
```

La motivación era que no fuese necesario ejecutar el make a cada rato,
y que detecte los cambios automáticamente en los archivos del proyecto.

Actualmente estaría ejecutando el `make all` cada segundo.
Quería proponer esta idea para no tener que estar tirando el `make all` a mano.

Saludos,

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?

¡Buenísima idea man! Hice una [búsqueda rápida](https://superuser.com/a/665208) y la forma más simple que encontré de hacer un `watch` es con una tool llamada `entr(1)`: https://github.com/eradman/entr/

Para instalarla es súper sencillo (lo probé tanto en las VMs como en mi Linux Mint 20.1): `sudo apt install entr`
Y para usarla simplemente le pasás los archivos que querés que observe (tienen que estar separados por `\n`):
```
find src/ -iname "*.c" | entr make
```
La única limitación que tiene es que si creás un nuevo archivo no tiene forma de observarlo a menos que reinicies, no me parece grave pero siempre es bueno saberlo.

Incluyendo esta regla en el makefile sale todo andando 10/10:
```makefile
watch: all
	echo "$(SOURCES) $(shell find $(IDIR) -iname "*.h")" | tr ' ' '\n' | entr make --no-print-directory
```

Este finde veo de armarlo para que quede bien prolijo y lo dejo en una branch de dev así no los vuelvo locos mandando releases cada 2 días jajaj

¡Saludos!

**Comment by RaniAgus** [comment]
**UPDATE** - Encontré una forma de hacer que se actualice incluso aunque se creen nuevos archivos usando el flag `-d` y envolviendo el llamado en un bucle infinito:
```makefile
.PHONY: watch
watch:
	while true; do \
	find $(SRCDIR) $(IDIR) | entr -d make --no-print-directory; \
	done;
```
