### ISSUE TITLE
Biblioteca compartida no reconoce a una función de una biblioteca estática

### ISSUE THREAD

**Issue by jlsuh** [RaniAgus/so-project-template#20]
Muy buenas Rani,
me acerco a consultar un caso que surgió probando cosas en el trabajo práctico de operativos.
Estuve desarrollando la `matelib`, más específicamente la función `mate_init`. Obtuve lo siguiente en los logs del makefile, en `carpincho-dummy` (el cual invoca `mate_init`):
```makefile
$ make start 
gcc -I../matelib/include/ -I../static/include/ -Iinclude/ -Wall -DDEBUG -g -o "bin/carpincho-dummy.out" obj/src/carpincho.o -L../matelib/bin/ -L../static/bin/ -lstatic -lmatelib -lcommons
/usr/bin/ld: ../matelib/bin//libmatelib.so: referencia a `conectar_a_servidor' sin definir
collect2: error: ld devolvió el estado de salida 1
make: *** [makefile:84: bin/carpincho-dummy.out] Error 1
```
Estructuramos el proyecto con los respectivos módulos, 1 biblioteca estática y 1 biblioteca compartida. La función `conectar_a_servidor` estaría en la biblioteca estática.

El siguiente sería los logs para `matelib` (ejecutado el `make clean all` desde el directorio raíz):
```makefile
make -C matelib all
make[1]: se entra en el directorio '/home/samsepi0l/Documentos/tp-2021-2c-La-Cosa-Operativa/matelib'
mkdir -pv obj/src/
mkdir: se ha creado el directorio 'obj'
mkdir: se ha creado el directorio 'obj/src/'
gcc -I../static/include/ -Iinclude/ -Wall -DDEBUG -g -c -fmessage-length=0 -fPIC -MMD -MP -MF"obj/src/matelib.d" -MT"obj/src/matelib.d" -o "obj/src/matelib.o" "src/matelib.c"
gcc -shared -o "bin/libmatelib.so" obj/src/matelib.o
make[1]: se sale del directorio '/home/samsepi0l/Documentos/tp-2021-2c-La-Cosa-Operativa/matelib'
```
Estuve viendo unos posts de stackoverflow y me encontré con [este post](https://stackoverflow.com/questions/8808691/can-i-build-a-shared-library-by-linking-static-libraries).

Siento que en la ante última línea de los logs le estaría faltando de alguna forma especificar que se compile contra la static library. Probé también cambiando el orden de compilación entre la biblioteca compartida y estática (para que primero compile la estática), pero honestamente no llegué a ninguna solución.
Quería saber si me podías dar una mano con este aspecto. Cualquier otra información que necesites estaré a disposición.

Saludos Rani !

**Comment by RaniAgus** [comment]
¡Buenas Joe! Ahí estuve haciendo pruebas (dejé el ejemplito en una [branch aparte](https://github.com/RaniAgus/so-project-template/tree/test) así lo tengo a mano) y al parecer lo importante no solo es el orden en que se compilan, sino también en el que se **linkean**. Siempre que lo probé lo hice con la variable `LIBRARIES` así, y me funcionó:

https://github.com/RaniAgus/so-project-template/blob/00f003362e1523f58547ab3eaf4f9e151b3ab4ce/project/makefile#L1-L2

Pero si uno intenta ponerlos al revés aparece el famoso `undefined reference to ''`; es como que tiene que ir "de más cerca a más lejos" para que funcione: primero la shared, después la static y al final las otras (commons, readline, pthread...).

Ahí vi que en el repo lo están usando en orden inverso, así que avisame si aplicando ese cambio se soluciona.

Saludos 😄

**Comment by jlsuh** [comment]
Muchísimas gracias Rani, ahí funcionó 🙏🏻
Pinnearé el issue desde el repo del tp.

Gracias Rani !

**Comment by RaniAgus** [comment]
¡Buenísimo! 🚀 
Me dejo como tarea pendiente el documentar cómo funciona `LIBRARIES`, mientras tanto dejo el issue pineado para que quede visible ☺️
