### ISSUE TITLE
Testear modulos - Posibilidad de integrar funciones de los modulos a los Tests

### ISSUE THREAD

**Issue by neverkas** [RaniAgus/so-project-template#21]
Buenas Rani, tuvimos un inconveniente con los tests en el TP de operativos, al tratar de testear los módulos, el problema es que no nos permite incluir las funciones de dichos modulos al usar la macro `#include` en los archivos de test.

Queríamos testear las funciones  del **módulo Kernel**, más específicamente del archivo `planificador.c`
y por tanto incluímos `planificador.h` en `planificador_tests.h` pero a la hora de compilar nos figura el siguiente log:

```
En el fichero incluido desde src/planificador_test.c:1:
include/planificador_test.h:9:10: error fatal: planificador.h: No existe el fichero o el directorio
    9 | #include "planificador.h"
      |          ^~~~~~~~~~~~~~~~

compilación terminada.
make[1]: *** [makefile:92: obj/src/planificador_test.o] Error 1
make: *** [makefile:7: tests] Error 2

```

Queríamos saber si es posible con la estructura presente de hacer esto, poder incluir códigos de módulos concretos en el módulo de tests.

Gracias

**Comment by RaniAgus** [comment]
¡Buenas! En el caso de un proyecto que no es biblioteca se complica un poco hacerlo aparte, ya que en el binario final hay que meter los `.c` de ambos (el original y el de tests).

Sin embargo, si usan CUnit pueden aprovechar de recibir algún parámetro en el `main` del planificador que diga que hay que correr los tests:
```
$ ./bin/planificador --run-tests
```
usando `argv`:
```c
int main(int argc, char* argv[]) {
  // argc: 2
  // argv: ["./bin/planificador", "--run-tests"]
}
```

Pero para CSpec no se me ocurre ninguna solución sencilla... Quizás vería de compilar todos los `*.c` salvo el que tenga el `main()` como lib estática y luego linkearla (un bardo 😕)

Saludos
