### ISSUE TITLE
Agregar soporte para CSpec

### ISSUE THREAD

**Issue by RaniAgus** [RaniAgus/so-project-template#22]
Agregar una variable `ENTRYPOINT` para diferenciar al archivo `*.c` que contiene el `main` del resto. De esa forma, se pueden compilar y linkear a un proyecto de test con CSpec.

**Comment by lalvarez-utn-frba** [comment]
Hola Agustín! Me gustaría testear esto, debería poder poner la carpeta test en cada project folder? o debería tener un project test en el root del repositorio? 
Usamos los pasos de tu repo para armar el template de nuestro tp, muchas gracias!

**Comment by RaniAgus** [comment]
︎¡Buenas @lalvarez-utn-frba ! ¿Cómo va?
Para probar lo que está en #17 primero hace falta cambiar todos los makefiles que estén en el repo (hice un refactor bastante groso xq me había quedado muy desordenado todo 😕). Te los podés traer descargando la branch como zip:
```
wget https://github.com/RaniAgus/so-project-template/archive/refs/heads/v2.5-patch.zip
unzip v2.5-patch.zip
```

Luego, en cuanto a la carpeta en donde dejar los tests, la idea es que lo definan ustedes seteando `PROJECT_PATH`:
https://github.com/RaniAgus/so-project-template/blob/afb0d7a21eb5fef3e91ad769112e985be86da95f/tests/makefile#L1

Por ejemplo, si lo quieren poner en cada project folder sería `..`, y si lo quieren poner en el root sería `../nombre-del-proyecto`.

¡Saludos!

**Comment by lalvarez-utn-frba** [comment]
Excelente! Gracias por la explicación! 
Nuestra idea es que cada módulo tenga sus propios tests, así que me hice una carpeta tests y me copie el makefile y el src del test de ejemplo en nuestra carpeta Kernel. Corrí `make start` estando en kernel/test y eso me levantó bien el test de ejemplo, voy a seguir por ese camino por ahora, cuando pueda me aplico el patch y te aviso si tengo algún problema.
Por otro lado, dejé PROJECT_PATH vacío en mi prueba inicial y anduvo igual, al menos corriendo los tests de esta forma.
Gracias por todo el laburo metido en este template, nos vino como anillo al dedo! 🚀

**Comment by RaniAgus** [comment]
¡Me alegra que les sirva!

Me olvidaba de algo: en el makefile de `project` hay una variable `ENTRYPOINT` en la que hay que especificar en qué archivo está el `main()`:
https://github.com/RaniAgus/so-project-template/blob/afb0d7a21eb5fef3e91ad769112e985be86da95f/project/makefile#L12-L17

Lo puse porque como CSpec es un framework (que tiene su propio `main()` para ejecutar los tests) hay que excluir esa función al compilar el proyecto de testing, sino va a fallar.

También, aclaro, el test de ejemplo funciona por sí solo porque puse esto para que vaya a buscar los `*.c` del proyecto original solo si `PROJECT_PATH` **no** está vacío (o sea, el ejemplo no va ir a buscar nada):
https://github.com/RaniAgus/so-project-template/blob/afb0d7a21eb5fef3e91ad769112e985be86da95f/tests/makefile#L27-L39

Son varios cambios respecto a la versión actual y tengo que tener tiempo para documentarlos bien antes de mergearlo 😅 

Saludos
