### ISSUE TITLE
Makefile + Git  - Compilación de módulos según rama de git

### ISSUE THREAD

**Issue by neverkas** [RaniAgus/so-project-template#23]
Buenas, estamos usando éste gran template para nuestro tp de sisop, y va genial, pero estabamos agregandole algunos features a medida que lo necesitamos. Queria saber si nos podías guiar de como adaptarlo con git, de paso quizás también te sirve como feature.

Sólo le agregamos algunas reglas para que según en que rama de git esté uno parado, te compile o no ciertos módulos, al parecer ejecuta las reglas en los directorios indicados, pero no del todo porque cuando vemos el directorio `bin` no aparece nada.

```
# este es nuestro makefile en la raíz de proyecto
GIT_BRANCH = $(shell git rev-parse --abbrev-ref HEAD) # new feature here
KERNEL_PROJECT=kernel
MEMORIA_PROJECT=memoria swamp
PROJECTS:=carpincho_dummy carpincho_dummy2 carpincho_dummy3 tests
LIBS=static matelib

all: $(PROJECTS) git_branch

$(PROJECTS): $(LIBS) $(CHECK_GIT)
	$(MAKE) --no-print-directory -C $@ all

 # new feature here
$(CHECK_GIT):
ifeq ($(GIT_BRANCH), dev/kernel)
  PROJECTS:=$(KERNEL_PROJECT) $(PROJECTS)
else ifeq ($(GIT_BRANCH), dev/memoria)
  PROJECTS:=$(MEMORIA_PROJECT) $(PROJECTS)
else ifeq ($(GIT_BRANCH), dev/swap)
  PROJECTS:=$(MEMORIA_PROJECT) $(PROJECTS)
else
  PROJECTS:=$(KERNEL_PROJECT) $(MEMORIA_PROJECT) $(PROJECTS)
endif

$(LIBS):
	$(MAKE) --no-print-directory -C $@ all

 # new feature here
git_branch:
	@echo "Usaste makefile para la rama \"$(GIT_BRANCH)\" y compilaste \"$(PROJECTS)\""

clean:
	$(foreach P, $(LIBS) $(PROJECTS), $(MAKE) --no-print-directory -C $P clean;)

release:
	$(foreach P, $(LIBS) $(PROJECTS), $(MAKE) --no-print-directory -C $P release;)

.PHONY: all $(PROJECTS) $(LIBS) $(CHECK_GIT) clean release git_branch
```

Por cierto, si sirve como otro feature, nosotros agregamos una regla extra en los makefile de cada módulo para que elimine los archivos generados por valgrind cuando debugeamos con vscode

```
clean: cleanvalgrindfiles
	$(RM) $(OBJDIR) $(BINARY)

cleanvalgrindfiles:
	$(RM) vgcore.*
```

Espero nos puedas guiar, y alguno de estos features sirva también en tu proyecto,
Gracias

**Comment by neverkas** [comment]
Creo que entendí mi error jaja, me había mareado un poco, por el hecho de tener una **macro** y **target** con mismo identificador. Cuando usabas el **target**  con `$` era para que se expanda, como con las macros normales, no? Nunca me había topado con eso e hice cualquier cosa xD.

**Comment by RaniAgus** [comment]
¡Buenas! ¿Cómo va?
1. Por lo que tengo entendido, el makefile lee las macros de arriba hacia abajo, o sea que para agregarle a `PROJECTS` los proyectos que ustedes quieran no hace falta que tengan un target. Hasta podés hacer que primero se agreguen los proyectos de cada módulo y luego [concatenar](https://www.gnu.org/software/make/manual/html_node/Appending.html#Appending) los que van para todos, creo que así quedaría más sencillo de leer:

```makefile
# Con != es lo mismo que si hicieras = $(shell ...)
GIT_BRANCH != git rev-parse --abbrev-ref HEAD

KERNEL_PROJECT=kernel
MEMORIA_PROJECT=memoria swamp

ifeq ($(GIT_BRANCH), dev/kernel)
  PROJECTS = $(KERNEL_PROJECT)
else ifeq ($(GIT_BRANCH), dev/memoria)
  PROJECTS = $(MEMORIA_PROJECT)
else ifeq ($(GIT_BRANCH), dev/swap)
  PROJECTS = $(MEMORIA_PROJECT)
else
  PROJECTS = $(KERNEL_PROJECT) $(MEMORIA_PROJECT)
endif

PROJECTS += carpincho_dummy carpincho_dummy2 carpincho_dummy3 tests
LIBS=static matelib

# Después de compilar todas las dependencias en $(PROJECTS), hace el echo
all: $(PROJECTS)
	@echo "Usaste makefile para la rama \"$(GIT_BRANCH)\" y compilaste \"$(PROJECTS)\""

$(PROJECTS): $(LIBS)
	$(MAKE) --no-print-directory -C $@ all

$(LIBS):
	$(MAKE) --no-print-directory -C $@ all

clean:
	$(foreach P, $(LIBS) $(PROJECTS), $(MAKE) --no-print-directory -C $P clean;)

release:
	$(foreach P, $(LIBS) $(PROJECTS), $(MAKE) --no-print-directory -C $P release;)

.PHONY: all $(PROJECTS) $(LIBS) clean release
```
2.
> Por cierto, si sirve como otro feature, nosotros agregamos una regla extra en los makefile de cada módulo para que elimine los archivos generados por valgrind cuando debugeamos con vscode

¡Buenísimo! Lo voy a tener en cuenta, quizás lo agregue a `make clean` directo, ya que si a `rm` le pasás varios archivos te los elimina todos:
```make
clean:
	$(RM) $(OBJDIR) $(BINARY) *.log vgcore.*
```
¿Cómo se generan esos cores? No conocía esa feature 😛 

3.
> Creo que entendí mi error jaja, me había mareado un poco, por el hecho de tener una macro y target con mismo identificador. Cuando usabas el target con $ era para que se expanda, como con las macros normales, no? Nunca me había topado con eso e hice cualquier cosa xD.

Claaro, estaban teniendo un target `$(CHECK_GIT)` cuyo valor al expandirlo es vacío:
```makefile
carpincho_dummy carpincho_dummy2 carpincho_dummy3 tests: static matelib
	make --no-print-directory -C $@ all
```
Cuando ponés [varios targets para la misma regla](https://web.mit.edu/gnu/doc/html/make_4.html#SEC35) es lo mismo que hacer lo siguiente:
```makefile
carpincho_dummy: static matelib
	make --no-print-directory -C carpincho_dummy all

carpincho_dummy2: static matelib
	make --no-print-directory -C carpincho_dummy2 all

carpincho_dummy3: static matelib
	make --no-print-directory -C carpincho_dummy3 all

tests: static matelib
	make --no-print-directory -C tests all

```
Entonces te estaba compilando solo lo que está en `PROJECTS` sin la parte del `if`, que no se estaba ejecutando nunca ya que aparece después de la regla `all`.

Espero haberme explicado bien 😅 

Saludos

**Comment by neverkas** [comment]
Genial, gracias más claro imposible :D ahí entendí ciertos detalles que se me pasaron por alto sobre makefile jaja :D

Esos cores no estoy seguro si se nos generaban porque probábamos el proyecto vía terminal con valgrind ó cuando debugeabamos con vscode, porque usábamos ambos al mismo tiempo jaja. El tema es que se nos iban acumulando en la raíz de cada módulo, y el clean por el momento parecía no contemplarlos (no me fijé del todo el makefile de los módulos porque no estoy a ese nivel jaja, sólo se lo básico así que agregué esa regla jeje)

Gracias por tomarte tu tiempo en explicarme, se agradece un montón :)
