### ISSUE TITLE
Static Lib referenciable como Shared Lib

### ISSUE THREAD

**Issue by jlsuh** [RaniAgus/so-project-template#29]
Muy buenas rani, yo de nuevo 😅
Encontré un caso (de casualidad y despistado) de redundancia entre las dos variables para referenciar a los dos tipos de bibliotecas.

### Precondición
Existe una biblioteca Utils que es una biblioteca estática.
### Settings
Se da la posibilidad, en otros módulos/bibliotecas, de:
```makefile
# En módulo Kernel
...
# Custom libraries' paths
SHARED_LIBPATHS=../utils
STATIC_LIBPATHS=
...
```
En otras palabras, es posible referenciar a una biblioteca estática como si fuese una biblioteca compartida.
El caso contrario (biblioteca dinámica referenciada como biblioteca estática) falla como debe.

---
Comprobé la integridad para los casos reflejados en #28 y todo anda joya 👍🏻

Saludos rani 😄

**Comment by RaniAgus** [comment]
> Comprobé la integridad para los casos reflejados en # 28 y todo anda joya 👍🏻

Vamosss.🚀🚀

> Es posible referenciar a una biblioteca estática como si fuese una biblioteca compartida.
> El caso contrario (biblioteca dinámica referenciada como biblioteca estática) falla como debe.

Está bien, en gcc ambas bibliotecas se referencian igual al momento de compilar (`-L` para incluir la ruta, `-I` para incluir los headers y `-l` para incluir la biblioteca en sí).

Lo que cambia es que al incluir una static library se compila todo el código en el binario, mientras que para la shared solo se chequean los headers y el código se carga en runtime, por lo que hace falta setear `LD_LIBRARY_PATH`.

Parte de esto está explicado en la guía, ¿creés que hace falta alguna revisión?

**Comment by jlsuh** [comment]
Genial rani 👍🏻

Quizás sea oportuno aclarar este caso en la sección de [Shared Libraries](https://raniagus.github.io/so-project-template-guide/guia/shared-libraries.html#agregar-una-shared-library-en-un-proyecto-existente) explicando esto mismo (para los futuros curiosos como yo que intenten clavar un clavo con una sierra 👀).

**Comment by RaniAgus** [comment]
Update de este issue antes de cerrar: otra diferencia entre `SHARED_LIBPATHS` y `STATIC_LIBPATHS` es que el makefile se basa en cada variable por separado para determinar si la dependencia es un `.so` o un `.a`:

https://github.com/RaniAgus/so-project-template/blob/02c25f54e6a8a0c8a2c88f2da308f1b897b2a5ad/compilation.mk#L4-L5

Y llama a su makefile para recompilarla de esta forma poco estética (?):
https://github.com/RaniAgus/so-project-template/blob/02c25f54e6a8a0c8a2c88f2da308f1b897b2a5ad/compilation.mk#L44-L47

Básicamente, una expansión "ejemplo" sería:
```makefile
# static lib : buscar los .c y .h en la carpeta de la izquierda, reemplazando 'bin' por 'src' o 'include' según corresponda 
../static/bin/libstatic.a : ../static/src/utils/hello.c ../static/include/utils/hello.h
 	# ejecutar make en la carpeta de la izquierda, sin 'bin'
 	make --no-print-directory -C ../static/
```
