### ISSUE TITLE
error al importar las commons

### ISSUE THREAD

**Issue by Ariel-Hab** [RaniAgus/so-project-template#34]
Hola, estube siguiendo tu tutorial sobre el template y la verdad esta kuy bien hecho. El problema es que me es imposible agregar las commons. Copie y pegue tu comando sin problemas (gcc src/main.c -o bin/ejemplo.out -lcommons) y tmb agregue la linea # Libraries
LIBS=commons. Por favor sabes cual seria el problema?

**Comment by RaniAgus** [comment]
¡Buenas! ¿Te referís a esta parte, no?

![image](https://user-images.githubusercontent.com/39303639/231296673-c7f73e97-69e7-44da-8132-5ccc76e81a90.png)

Lo que intentaba decir es que dentro del archivo `settings.mk` que está dentro del template **ya hay una variable `LIBS`** que está vacía y pueden agregar ahí las bibliotecas que necesiten:

https://github.com/RaniAgus/so-project-template/blob/0622e4b1893764ccbf683bbc77ff37bbe95e2551/src/project/settings.mk#L1-L2

No es la idea ejecutar la línea de `gcc`, sino mostrar un poco qué es lo que ocurre al editar esa variable, ya que si le agregan `commons` y ejecutan `make` van a ver algo como:

```
gcc -g -Wall -DDEBUG -c -o "obj/main.o" src/main.c -I./src
gcc -g -Wall -DDEBUG -o "bin/project.out" obj/main.o -I./src   -lcommons
```

¿Se entiende la idea más o menos o crees que debería rewordearlo un toque? 😅

**Comment by Ariel-Hab** [comment]
primero que todo gracias por responder tan rapido. Ahi me fije y tenes razon, despues de agregar "LIBS=commons" si corro make me aparecen esas dos lineas de gcc. El problema es que cuando lo quiero buildear en vscode me tira error de que no reconoce los comandos de la libreria (en este caso solo estoy importando logs.h y estoy probando un simple log)

**Comment by Ariel-Hab** [comment]
Hola, queria avisarte que por error mio pense que esa seccion era para vscode. Ahi lo probe en eclipse y anda joya. Sos un groso por hacer estos tutoriales
Aguante nagi

**Comment by RaniAgus** [comment]
Eaaaaa 🙌🏻 
Igual debería andar tanto para Eclipse como para VSCode... Si querés copiá y pegá el texto del error y lo vemos. Sino, si estás bien con Eclipse podés cerrar el issue :)

**Comment by Ariel-Hab** [comment]
![image](https://user-images.githubusercontent.com/129193075/231480072-b1673a8a-d208-4c2e-8a51-1f394cd12cad.png)

Este es el error que me tira en vscode. En eclipse arme el tp0 y me anduvo sin ningun problema, pero cuando lo buildeo aca me tira todos estos errores

**Comment by RaniAgus** [comment]
Por lo que veo acá, no se está usando el makefile para compilar, sino una tarea del plugin de C/C++ que se corre por defecto cuando no encuentra ningún `tasks.json` con tareas de tipo build:

![image](https://user-images.githubusercontent.com/39303639/231485274-5a10ce3f-2815-4d0e-b6ae-c2b5b076a9a8.png)

Creo que está ocurriendo eso porque veo que tenés abierto en VSCode la carpeta del repo con todos los proyectos:

![image](https://user-images.githubusercontent.com/39303639/231483130-ff83a924-be5e-427a-aed5-37beec050a81.png)

La idea es agregar la carpeta de cada proyecto (consola, kernel, etc...) por separado como en [la guía anterior](https://raniagus.github.io/so-project-template/guia/importar-proyecto#visual-studio-code), así para compilar les toma la carpeta `.vscode` de cada uno:

![image](https://user-images.githubusercontent.com/39303639/231486077-17951f82-4012-4407-95de-0776dfee1569.png)

Si está bien importado, en la pestaña de Debug les debería aparecer algo así:

![image](https://user-images.githubusercontent.com/39303639/231484054-53fa55d0-dd8a-4070-9e84-11b8d29dc80c.png)

Pero en vez de haber dos project habría dos para consola, kernel, cpu, etc.

Si querés probá de cerrar ese workspace que tenés hecho y seguir la guía de nuevo desde cero 👍🏻

**Comment by Ariel-Hab** [comment]
Me ando!!! mil gracias, habia entendido que en"add folder to workspace" habia que agregar la carpeta raiz. Sos un capo gracias
